# Generated by Django 2.0.3 on 2018-03-18 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime(2018, 3, 18, 18, 52, 0, 22826, tzinfo=utc), verbose_name='Дата создания')),
                ('title', models.CharField(max_length=120, verbose_name='Название статьи')),
                ('photo', models.ImageField(upload_to='images/articles', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.Author', verbose_name='Автор')),
                ('category', models.ManyToManyField(related_name='article', to='categories.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-created'],
            },
        ),
    ]
